stages:
  - release

variables:
  ZIP_PREFIX: "tbs_webpressor"

create_release_zip:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
      when: always
  script:
    - echo "Creating zip for tag $CI_COMMIT_TAG"
    - mkdir release
    - zip -r "release/${ZIP_PREFIX}-${CI_COMMIT_TAG}.zip" . \
        -x "react-admin/*" ".gitignore" ".gitlab-ci.yml" ".git/*"
    - echo "Zip created at release/${ZIP_PREFIX}-${CI_COMMIT_TAG}.zip"
  artifacts:
    paths:
      - release/${ZIP_PREFIX}-${CI_COMMIT_TAG}.zip

release:
  stage: release
  needs: ["create_release_zip"]
  rules:
    - if: $CI_COMMIT_TAG
      when: always
  script:
    - echo "Creating GitLab release for tag $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    name: "Release $CI_COMMIT_TAG"
    description: "Automated release for tag $CI_COMMIT_TAG"
    assets:
      links:
        - name: "${ZIP_PREFIX}-${CI_COMMIT_TAG}.zip"
          url: "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/release/${ZIP_PREFIX}-${CI_COMMIT_TAG}.zip"
