stages:
  - release

create_release:
  stage: release
  image: alpine:latest
  script:
    # Install required tools
    - apk add --no-cache git zip bash
    
    # Only run on tags
    - |
      if [[ "$CI_COMMIT_TAG" == "" ]]; then
        echo "This job only runs on tags"
        exit 0
      fi
    
    # Create a temp directory for our release
    - mkdir -p release_temp
    
    # Clone the repository to our temp directory
    - git clone $CI_REPOSITORY_URL release_temp/repo
    - cd release_temp/repo
    
    # Checkout the specific tag
    - git checkout $CI_COMMIT_TAG
    
    # Create a directory with the base name (without tag)
    - mkdir -p ../tbs_webpressor
    
    # Copy all files except excluded ones
    - |
      find . -type f -not -path "./react-admin/*" \
        -not -name ".gitignore" \
        -not -name ".gitlab-ci.yml" \
        -not -path "./.git/*" | while read file; do
        mkdir -p "../tbs_webpressor/$(dirname "$file")"
        cp "$file" "../tbs_webpressor/$file"
      done
    
    # Create the zip file with tag version in the name
    - cd ..
    - zip -r "tbs_webpressor_${CI_COMMIT_TAG}.zip" tbs_webpressor
    
    # Move the zip file to artifacts directory
    - mkdir -p ../../artifacts
    - mv "tbs_webpressor_${CI_COMMIT_TAG}.zip" ../../artifacts/
    
    # Clean up
    - cd ../..
    - rm -rf release_temp
  
  artifacts:
    paths:
      - artifacts/tbs_webpressor_${CI_COMMIT_TAG}.zip
    expire_in: 1 week
  
  rules:
    - if: $CI_COMMIT_TAG