name: Create Release Zip

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare release folder
        run: |
          mkdir -p tbs_webpressor
          rsync -av ./ tbs_webpressor/ \
            --exclude='react-admin' \
            --exclude='.git' \
            --exclude='.gitignore' \
            --exclude='.gitlab-ci.yml' \
            --exclude='.github' \
            --exclude='tbs_webpressor_*'  # Avoid previous zips

      - name: Get tag and zip
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          ZIP_NAME="tbs_webpressor_${TAG_NAME}.zip"
          zip -r "$ZIP_NAME" tbs_webpressor
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Create GitHub Release and Upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
