name: Create Release Zip

on:
  push:
    tags:
      - '*'

permissions:
  contents: write  # Required to create releases and upload assets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up tag name and zip file
        id: prepare
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          ZIP_NAME="tbs_webpressor_${TAG_NAME}.zip"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Create release folder
        run: |
          mkdir release
          rsync -av --exclude='react-admin' \
                    --exclude='.gitignore' \
                    --exclude='.github' \
                    ./ release/

      - name: Zip release
        run: |
          cd release
          zip -r "../$ZIP_NAME" .

      - name: Create GitHub Release and Upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.TAG_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
